name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Environnement de travail (Ubuntu)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Vérification du code du repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Configuration de l'environnement Python
      with:
        python-version: '3.8'  # Vous pouvez spécifier la version de Python ici

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Mise à jour de pip
        pip install -r requirements.txt     # Installation des dépendances depuis requirements.txt

    - name: Set up virtual environment
      run: |
        python3 -m venv venv  # Création de l'environnement virtuel
        ./venv/bin/pip install --upgrade pip  # Mise à jour de pip dans l'environnement virtuel
        ./venv/bin/pip install -r requirements.txt  # Installation des dépendances dans l'environnement virtuel

    - name: Run Makefile prepare
      run: |
        make prepare  # Préparation des données

    - name: Run Makefile train
      run: |
        make train  # Entraînement du modèle

    - name: Run Makefile evaluate
      run: |
        make evaluate  # Évaluation du modèle

    - name: Run tests
      run: |
        make test  # Exécution des tests unitaires

    - name: Clean up
      run: |
        make clean  # Nettoyage des fichiers temporaires et environnement
