name: MLOps CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run Makefile pipeline
        run: |
          make setup
          make verify
          make prepare
          make train
          make test
          make evaluate

